export const UPLOAD_FOLDERS = {
  PRODUCTS: 'products',
  USERS: 'users',
  REVIEWS: 'reviews',
  ICONS: 'icons',
  COUPONS: 'coupons',
  BLOGS: 'blogs',
  BANNERS: 'banners',
  DESIGNS: 'designs',
  SUBCATEGORIES: 'subcategories',
  CATEGORIES: 'categories',
  CHARTS: 'charts',
  TESTIMONIALS: 'testimonials',
  BRANDS: 'brands',
  OTHERS: 'others',
};
